version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    networks:
      - web
    labels:
      # Activer Traefik pour ce conteneur
      - "traefik.enable=true"
      
      # Routage HTTP
      - "traefik.http.routers.portfolio.rule=Host(`trapuce.tech`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.routers.portfolio.middlewares=portfolio-redirect"
      
      # Routage HTTPS
      - "traefik.http.routers.portfolio-secure.rule=Host(`trapuce.tech`)"
      - "traefik.http.routers.portfolio-secure.entrypoints=websecure"
      - "traefik.http.routers.portfolio-secure.tls=true"
      - "traefik.http.routers.portfolio-secure.tls.certresolver=myresolver"
      
      # Redirection HTTP vers HTTPS
      - "traefik.http.middlewares.portfolio-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.portfolio-redirect.redirectscheme.permanent=true"
      
      # Service port
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"

networks:
  web:
    external: true

